# GitHub Pages Configuration for BTF5965 Presence System

# Site settings
title: "BTF5965 Tax Law Tutorial"
description: "Student presence tracking system for Tax Law tutorial classes"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge

# Exclude files from processing
exclude:
  - project_plan.md
  - node_modules/
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md

# Include files that start with underscores
include:
  - _config.yml

# Plugin settings
plugins:
  - jekyll-sitemap
  - jekyll-feed

# SEO settings
lang: en
author: "BTF5965 Course Team"

# Social media and meta tags
social:
  name: "BTF5965 Tax Law Tutorial"
  links:
    - https://github.com/yourusername/btf5965-presence-system

# Google Analytics (optional - add your tracking ID)
# google_analytics: UA-XXXXXXXX-X

# Custom variables
course:
  code: "BTF5965"
  name: "Tax Law Tutorial"
  semester: "2025"
  
# Security headers (if supported by hosting)
headers:
  X-Frame-Options: "SAMEORIGIN"
  X-Content-Type-Options: "nosniff"
  X-XSS-Protection: "1; mode=block"

